# API configuration for F.A.D.E

# LLM API settings - These will be overridden by environment variables
openai:
  api_key: "${OPENAI_API_KEY}"
  organization: "${OPENAI_ORGANIZATION}"
  base_url: "https://api.openai.com/v1"
  models:
    default: "gpt-4-turbo"
    molecule_generation: "gpt-4-turbo"
    result_interpretation: "gpt-4-turbo"

anthropic:
  api_key: "${ANTHROPIC_API_KEY}"
  base_url: "https://api.anthropic.com"
  models:
    default: "claude-3-sonnet-20240229"
    molecule_generation: "claude-3-opus-20240229"
    result_interpretation: "claude-3-sonnet-20240229"

# Database API settings
uniprot:
  base_url: "https://rest.uniprot.org/uniprotkb/"
  timeout: 30
  retry_attempts: 3
  retry_delay: 2

pdb:
  base_url: "https://data.rcsb.org/rest/v1/core/entry/"
  timeout: 30
  retry_attempts: 3
  retry_delay: 2

pubchem:
  base_url: "https://pubchem.ncbi.nlm.nih.gov/rest/pug"
  timeout: 30
  retry_attempts: 3
  retry_delay: 2

chembl:
  base_url: "https://www.ebi.ac.uk/chembl/api/data"
  timeout: 30
  retry_attempts: 3
  retry_delay: 2

# API rate limiting
rate_limits:
  openai:
    requests_per_minute: 60
    tokens_per_minute: 90000
  anthropic:
    requests_per_minute: 40
    tokens_per_minute: 100000
  uniprot:
    requests_per_minute: 30
  pdb:
    requests_per_minute: 30
  pubchem:
    requests_per_minute: 5
  chembl:
    requests_per_minute: 5
