# Environment configuration for F.A.D.E

# Paths to executables and containers
paths:
  alphafold3: "/shared/container_repository/AlphaFold/alphafold3.sif"
  schrodinger: "/shared/EL9/explorer/schrodinger/2024-4"
  scratch: "/scratch/${USER}"
  data: "${PROJECT_ROOT}/data"
  logs: "${PROJECT_ROOT}/logs"
  outputs: "${PROJECT_ROOT}/data/outputs"

# Environment modules to load
modules:
  structure_prediction:
    - "miniconda3/24.11.1"
    - "cuda/12.3.0"
  docking:
    - "schrodinger/2024-4"
  python:
    - "python/3.13.5"

# Container execution settings
containers:
  alphafold3:
    command: "singularity exec --nv ${paths.alphafold3}"
    bind_paths:
      - "${paths.scratch}:/scratch"
      - "${paths.data}/inputs:/inputs"
      - "${paths.data}/outputs:/outputs"
    environment:
      TF_FORCE_UNIFIED_MEMORY: "1"
      XLA_PYTHON_CLIENT_MEM_FRACTION: "4.0"

# SLURM job settings
slurm:
  common:
    account: "${SLURM_ACCOUNT}"
    mail_type: "END,FAIL"
    mail_user: "${USER}@northeastern.edu"
  
  structure_prediction:
    partition: "gpu"
    constraint: "gpu:v100"
    gres: "gpu:1"
    cpus_per_task: 4
    mem: "32G"
    time: "04:00:00"
  
  docking:
    partition: "compute"
    cpus_per_task: 8
    mem: "16G"
    time: "02:00:00"
  
  pipeline:
    partition: "compute"
    cpus_per_task: 2
    mem: "8G"
    time: "00:30:00"
